/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Main_Menue_Facture (void)
{
  GtkWidget *Main_Menue_Facture;
  GtkWidget *fixed1;
  GtkWidget *treeview_facture;
  GtkWidget *Ajouter_facture;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *button_Edit_facture;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *button_Delete_Facture;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;

  Main_Menue_Facture = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Main_Menue_Facture), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Main_Menue_Facture), fixed1);

  treeview_facture = gtk_tree_view_new ();
  gtk_widget_show (treeview_facture);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview_facture, 0, 72);
  gtk_widget_set_size_request (treeview_facture, 640, 264);

  Ajouter_facture = gtk_button_new ();
  gtk_widget_show (Ajouter_facture);
  gtk_fixed_put (GTK_FIXED (fixed1), Ajouter_facture, 48, 352);
  gtk_widget_set_size_request (Ajouter_facture, 80, 33);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (Ajouter_facture), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  button_Edit_facture = gtk_button_new ();
  gtk_widget_show (button_Edit_facture);
  gtk_fixed_put (GTK_FIXED (fixed1), button_Edit_facture, 250, 352);
  gtk_widget_set_size_request (button_Edit_facture, 100, 33);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_Edit_facture), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  button_Delete_Facture = gtk_button_new ();
  gtk_widget_show (button_Delete_Facture);
  gtk_fixed_put (GTK_FIXED (fixed1), button_Delete_Facture, 450, 352);
  gtk_widget_set_size_request (button_Delete_Facture, 100, 33);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_Delete_Facture), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview_facture, "row_activated",
                    G_CALLBACK (on_treeview_facture_row_activated),
                    NULL);
  g_signal_connect ((gpointer) Ajouter_facture, "clicked",
                    G_CALLBACK (on_Ajouter_facture_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_Edit_facture, "clicked",
                    G_CALLBACK (on_button_Edit_facture_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_Delete_Facture, "clicked",
                    G_CALLBACK (on_button_Delete_Facture_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Main_Menue_Facture, Main_Menue_Facture, "Main_Menue_Facture");
  GLADE_HOOKUP_OBJECT (Main_Menue_Facture, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Main_Menue_Facture, treeview_facture, "treeview_facture");
  GLADE_HOOKUP_OBJECT (Main_Menue_Facture, Ajouter_facture, "Ajouter_facture");
  GLADE_HOOKUP_OBJECT (Main_Menue_Facture, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Main_Menue_Facture, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Main_Menue_Facture, image1, "image1");
  GLADE_HOOKUP_OBJECT (Main_Menue_Facture, label1, "label1");
  GLADE_HOOKUP_OBJECT (Main_Menue_Facture, button_Edit_facture, "button_Edit_facture");
  GLADE_HOOKUP_OBJECT (Main_Menue_Facture, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Main_Menue_Facture, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Main_Menue_Facture, image2, "image2");
  GLADE_HOOKUP_OBJECT (Main_Menue_Facture, label2, "label2");
  GLADE_HOOKUP_OBJECT (Main_Menue_Facture, button_Delete_Facture, "button_Delete_Facture");
  GLADE_HOOKUP_OBJECT (Main_Menue_Facture, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Main_Menue_Facture, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Main_Menue_Facture, image3, "image3");
  GLADE_HOOKUP_OBJECT (Main_Menue_Facture, label3, "label3");

  return Main_Menue_Facture;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed2;
  GtkWidget *entry_Ref_Facture;
  GtkObject *spinbutton_jour_facture_adj;
  GtkWidget *spinbutton_jour_facture;
  GtkObject *spinbutton_mois_facture_adj;
  GtkWidget *spinbutton_mois_facture;
  GtkObject *spinbutton_anne_facture_adj;
  GtkWidget *spinbutton_anne_facture;
  GtkWidget *entry_montant_facture;
  GtkWidget *entry_code_postale_facture;
  GtkWidget *entry_ville_facture;
  GtkWidget *entry_pays_facture;
  GtkWidget *label4000;
  GtkWidget *label5000;
  GtkWidget *label6000;
  GtkWidget *label10000;
  GtkWidget *label9000;
  GtkWidget *label8000;
  GtkWidget *label7000;
  GtkWidget *combobox_facture;
  GtkWidget *button_save_facture;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label11;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2), fixed2);

  entry_Ref_Facture = gtk_entry_new ();
  gtk_widget_show (entry_Ref_Facture);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_Ref_Facture, 208, 48);
  gtk_widget_set_size_request (entry_Ref_Facture, 172, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Ref_Facture), 8226);

  spinbutton_jour_facture_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_jour_facture = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_jour_facture_adj), 1, 0);
  gtk_widget_show (spinbutton_jour_facture);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_jour_facture, 208, 96);
  gtk_widget_set_size_request (spinbutton_jour_facture, 70, 34);

  spinbutton_mois_facture_adj = gtk_adjustment_new (3, 1, 12, 1, 10, 10);
  spinbutton_mois_facture = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mois_facture_adj), 1, 0);
  gtk_widget_show (spinbutton_mois_facture);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_mois_facture, 300, 96);
  gtk_widget_set_size_request (spinbutton_mois_facture, 70, 34);

  spinbutton_anne_facture_adj = gtk_adjustment_new (2018, 2010, 2030, 1, 10, 10);
  spinbutton_anne_facture = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_anne_facture_adj), 1, 0);
  gtk_widget_show (spinbutton_anne_facture);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_anne_facture, 400, 96);
  gtk_widget_set_size_request (spinbutton_anne_facture, 70, 34);

  entry_montant_facture = gtk_entry_new ();
  gtk_widget_show (entry_montant_facture);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_montant_facture, 207, 200);
  gtk_widget_set_size_request (entry_montant_facture, 170, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_montant_facture), 8226);

  entry_code_postale_facture = gtk_entry_new ();
  gtk_widget_show (entry_code_postale_facture);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_code_postale_facture, 208, 248);
  gtk_widget_set_size_request (entry_code_postale_facture, 170, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_code_postale_facture), 8226);

  entry_ville_facture = gtk_entry_new ();
  gtk_widget_show (entry_ville_facture);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_ville_facture, 208, 300);
  gtk_widget_set_size_request (entry_ville_facture, 170, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_ville_facture), 8226);

  entry_pays_facture = gtk_entry_new ();
  gtk_widget_show (entry_pays_facture);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_pays_facture, 208, 352);
  gtk_widget_set_size_request (entry_pays_facture, 170, 34);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_pays_facture), 8226);

  label4000 = gtk_label_new (_("R\303\251f fact :"));
  gtk_widget_show (label4000);
  gtk_fixed_put (GTK_FIXED (fixed2), label4000, 80, 48);
  gtk_widget_set_size_request (label4000, 100, 30);

  label5000 = gtk_label_new (_("Date de fact :"));
  gtk_widget_show (label5000);
  gtk_fixed_put (GTK_FIXED (fixed2), label5000, 80, 100);
  gtk_widget_set_size_request (label5000, 100, 30);

  label6000 = gtk_label_new (_("Moyen de paiment :"));
  gtk_widget_show (label6000);
  gtk_fixed_put (GTK_FIXED (fixed2), label6000, 40, 150);
  gtk_widget_set_size_request (label6000, 150, 30);

  label10000 = gtk_label_new (_("Pays :"));
  gtk_widget_show (label10000);
  gtk_fixed_put (GTK_FIXED (fixed2), label10000, 80, 350);
  gtk_widget_set_size_request (label10000, 100, 30);

  label9000 = gtk_label_new (_("Ville :"));
  gtk_widget_show (label9000);
  gtk_fixed_put (GTK_FIXED (fixed2), label9000, 80, 304);
  gtk_widget_set_size_request (label9000, 100, 30);

  label8000 = gtk_label_new (_("Code postale :"));
  gtk_widget_show (label8000);
  gtk_fixed_put (GTK_FIXED (fixed2), label8000, 80, 250);
  gtk_widget_set_size_request (label8000, 100, 30);

  label7000 = gtk_label_new (_("Montant :"));
  gtk_widget_show (label7000);
  gtk_fixed_put (GTK_FIXED (fixed2), label7000, 88, 200);
  gtk_widget_set_size_request (label7000, 100, 30);

  combobox_facture = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_facture);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox_facture, 216, 152);
  gtk_widget_set_size_request (combobox_facture, 200, 33);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_facture), _("Cheque "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_facture), _("Espece"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_facture), _("Carte Bancaire"));

  button_save_facture = gtk_button_new ();
  gtk_widget_show (button_save_facture);
  gtk_fixed_put (GTK_FIXED (fixed2), button_save_facture, 416, 424);
  gtk_widget_set_size_request (button_save_facture, 120, 33);
  gtk_button_set_focus_on_click (GTK_BUTTON (button_save_facture), FALSE);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_save_facture), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox4), label11, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_save_facture, "clicked",
                    G_CALLBACK (on_button_save_facture_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, entry_Ref_Facture, "entry_Ref_Facture");
  GLADE_HOOKUP_OBJECT (window2, spinbutton_jour_facture, "spinbutton_jour_facture");
  GLADE_HOOKUP_OBJECT (window2, spinbutton_mois_facture, "spinbutton_mois_facture");
  GLADE_HOOKUP_OBJECT (window2, spinbutton_anne_facture, "spinbutton_anne_facture");
  GLADE_HOOKUP_OBJECT (window2, entry_montant_facture, "entry_montant_facture");
  GLADE_HOOKUP_OBJECT (window2, entry_code_postale_facture, "entry_code_postale_facture");
  GLADE_HOOKUP_OBJECT (window2, entry_ville_facture, "entry_ville_facture");
  GLADE_HOOKUP_OBJECT (window2, entry_pays_facture, "entry_pays_facture");
  GLADE_HOOKUP_OBJECT (window2, label4000, "label4000");
  GLADE_HOOKUP_OBJECT (window2, label5000, "label5000");
  GLADE_HOOKUP_OBJECT (window2, label6000, "label6000");
  GLADE_HOOKUP_OBJECT (window2, label10000, "label10000");
  GLADE_HOOKUP_OBJECT (window2, label9000, "label9000");
  GLADE_HOOKUP_OBJECT (window2, label8000, "label8000");
  GLADE_HOOKUP_OBJECT (window2, label7000, "label7000");
  GLADE_HOOKUP_OBJECT (window2, combobox_facture, "combobox_facture");
  GLADE_HOOKUP_OBJECT (window2, button_save_facture, "button_save_facture");
  GLADE_HOOKUP_OBJECT (window2, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window2, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window2, image4, "image4");
  GLADE_HOOKUP_OBJECT (window2, label11, "label11");

  return window2;
}

